Repository hellhub-collective/api, pull requests merged in 2024-04, with the labels that each got.

#33 Data: Move Liberty Ridge to Meridian sector
  src/static/json/sectors.json
Labels: enhancement

#34 fix: reduce deployment memory usage
  bun.lockb
  package.json
  src/classes/rate-limit.ts
  src/classes/request-cache.ts
  src/controllers/assignments.ts
  src/controllers/attacks.ts
  src/controllers/events.ts
  src/controllers/factions.ts
  src/controllers/orders.ts
  src/controllers/planets.ts
  src/controllers/reports.ts
  src/controllers/sectors.ts
  src/controllers/statistics.ts
  src/controllers/stratagems.ts
  src/controllers/war.ts
  src/index.ts
  src/jobs/refresh.ts
  src/middleware/cache.ts
  src/middleware/rate-limit.ts
  src/middleware/request-cache.ts
  src/utils/request-cache.ts
Labels: enhancement

#35 fix: ensure cache is served until poll is complete
  src/jobs/refresh.ts
  src/utils/request-cache.ts
Labels: bug

#36 feat: add logging middleware
  bun.lockb
  package.json
  src/index.ts
  src/jobs/refresh.ts
  src/middleware/logger.ts
Labels: enhancement

#37 fix: ensure newest report data is available and properly sorted
  src/utils/generate.ts
  src/utils/refresh.ts
Labels: bug

#38 feat: add liberation fields
  .github/workflows/tests.yml
  Dockerfile
  prisma/migrations/20240405123412_liberation/migration.sql
  prisma/schema.prisma
  src/types/history.ts
  src/utils/generate.ts
  src/utils/refresh.ts
Labels: enhancement

#40 feat: add planet biomes and environmental effects
  prisma/migrations/20240416070907_biomes/migration.sql
  prisma/schema.prisma
  src/controllers/biomes.ts
  src/controllers/effects.ts
  src/index.ts
  src/routes/biomes.ts
  src/routes/effects.ts
  src/static/json/biomes.json
  src/static/json/effects.json
  src/static/json/planets.json
  src/utils/generate.ts
Labels: enhancement

#41 feat: implement sentry for production builds
  .gitignore
  Dockerfile
  bun.lockb
  package.json
  scripts/build.ts
  src/controllers/assignments.ts
  src/controllers/attacks.ts
  src/controllers/biomes.ts
  src/controllers/effects.ts
  src/controllers/events.ts
  src/controllers/factions.ts
  src/controllers/orders.ts
  src/controllers/planets.ts
  src/controllers/reports.ts
  src/controllers/sectors.ts
  src/controllers/statistics.ts
  src/controllers/stratagems.ts
  src/controllers/war.ts
  src/index.ts
  src/jobs/refresh.ts
  src/middleware/files.ts
  src/utils/sentry.ts
Labels: enhancement

#42 fix: resolve dockerfile issues
  Dockerfile
  src/utils/sentry.ts
Labels: bug

#43 fix: install ca-certificates package to fix SSL issues
  Dockerfile
Labels: bug

#45 feat: implement sentry middleware
  bun.lockb
  package.json
  src/controllers/assignments.ts
  src/controllers/attacks.ts
  src/controllers/biomes.ts
  src/controllers/effects.ts
  src/controllers/events.ts
  src/controllers/factions.ts
  src/controllers/orders.ts
  src/controllers/planets.ts
  src/controllers/reports.ts
  src/controllers/sectors.ts
  src/controllers/statistics.ts
  src/controllers/stratagems.ts
  src/controllers/war.ts
  src/index.ts
  src/jobs/refresh.ts
  src/utils/sentry.ts
Labels: enhancement

#46 feat: add sentry performance tracing
  src/index.ts
  src/middleware/tracing.ts
  src/utils/sentry.ts
Labels: enhancement

#47 refractor: decrease sentry trace sample rate
  src/utils/sentry.ts
Labels: refractor

#48 feat: implement cron job oberservation routes
  bun.lockb
  package.json
  src/controllers/crons.ts
  src/index.ts
  src/jobs/index.ts
  src/jobs/refresh.ts
  src/routes/crons.ts
Labels: feature

#49 refractor: update readme file with postman badge
  README.md
Labels: documentation

#50 feat: add planet texture images in webp format
  .github/workflows/tests.yml
  Dockerfile
  prisma/migrations/20240422103412_textures/migration.sql
  prisma/schema.prisma
  src/controllers/stratagems.ts
  src/static/json/planets.json
  src/utils/generate.ts
Labels: feature

#52 fix: manually run garbage collector after cron job
  src/jobs/index.ts
Labels: bug

#53 chore(deps): bump dependencies to latest versions
  bun.lockb
  package.json
Labels: dependencies

#55 feat: add assignment tasks
  Dockerfile
  bun.lockb
  package.json
  prisma/migrations/20240424085109_tasks/migration.sql
  prisma/schema.prisma
  src/controllers/assignments.ts
  src/jobs/index.ts
  src/middleware/logger.ts
  src/utils/generate.ts
  src/utils/refresh.ts
Labels: feature

#56 fix: resolve issues with docker deployment process
  Dockerfile
  bun.lockb
  package.json
  prisma/schema.prisma
Labels: bug

#58 chore(release): prepare source code for version 3.0.0
  .github/workflows/tests.yml
  .gitignore
  Dockerfile
  bun.lockb
  package.json
  scripts/build.ts
  scripts/init.ts
  src/classes/rate-limit.ts
  src/classes/request-cache.ts
  src/controllers/assignments.ts
  src/controllers/attacks.ts
  src/controllers/biomes.ts
  src/controllers/effects.ts
  src/controllers/events.ts
  src/controllers/factions.ts
  src/controllers/orders.ts
  src/controllers/planets.ts
  src/controllers/reports.ts
  src/controllers/sectors.ts
  src/controllers/statistics.ts
  src/controllers/stratagems.ts
  src/controllers/war.ts
  src/middleware/rate-limit.ts
  src/middleware/request-cache.ts
  src/utils/database.ts
  src/utils/game-date.ts
  src/utils/generate.ts
  src/utils/refresh.ts
  src/utils/request-cache.ts
  src/utils/sentry.ts
Labels: feature

#59 fix: replace broken status badge in readme
  README.md
Labels: bug
